### ISSUE TITLE
Add this gem to the OpenTelemetry registry

### ISSUE THREAD

**Issue by fbogsany** [DataDog/dd-opentelemetry-exporter-ruby#7]
https://opentelemetry.io/get-involved/#registry

Related: https://github.com/open-telemetry/opentelemetry-ruby/issues/304

**Comment by ericmustin** [comment]
@fbogsany Yup will try to make a PR with this shortly, will also try to add the instrumentation(formerly adapters) as well while i'm there. Feel free to assign that issue to me on https://github.com/open-telemetry/opentelemetry-ruby/issues/304
